### ISSUE TITLE
pdf build时出错，字体问题

### ISSUE THREAD

**Issue by hao203** [XiangyunHuang/ElegantBookdown#22]
! Package fontspec Error: The font "Adobe Song Std" cannot be found.

Error: LaTeX failed to compile elegantbookdown.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See elegantbookdown.log for more info.
Execution halted

Exited with status 1.

看样子是字体无法安装的问题，不知道为什么

**Comment by lief-y** [comment]
看一下你电脑上有没有 Adobe Song Std， 没有的话把 preamble.tex 文件里关于字体设置的代码换成你电脑上有的应该就可以了。

**Comment by hao203** [comment]
> 看一下你电脑上有没有 Adobe Song Std， 没有的话把 preamble.tex 文件里关于字体设置的代码换成你电脑上有的应该就可以了。

谢谢。我看到.travis.yml也有字体的设置，和下载。但似乎没有用

**Comment by XiangyunHuang** [comment]
字体在 preamble.tex 文件里是设置了的，请看

https://github.com/XiangyunHuang/ElegantBookdown/blob/9cde8a29e7c6ce445212c94c63340806bd78bad2/preamble.tex#L9-L22

**Comment by hao203** [comment]
> 字体在 preamble.tex 文件里是设置了的，请看
> 

谢谢湘云姐姐

**Comment by hao203** [comment]
> 字体在 preamble.tex 文件里是设置了的，请看
> 
我的解决方法是，按您[fonts项目](https://github.com/XiangyunHuang/fonts/releases/tag/v0.1)
下载之后，每个字体，右键-为所有用户安装。这样就解决了

**Comment by XiangyunHuang** [comment]
> > 字体在 preamble.tex 文件里是设置了的，请看
> 
> 谢谢湘云姐姐

不客气，名字有性别误导性，我是男的 😅
