### ISSUE TITLE
此处的文武线是什么效果？

### ISSUE THREAD

**Issue by A-Pai** [XiangyunHuang/ElegantBookdown#28]
代码是：
![image](https://user-images.githubusercontent.com/5112397/156922501-249edb45-3b10-4442-9ef1-8c3c43dd701b.png)
得到的效果是：
![image](https://user-images.githubusercontent.com/5112397/156922544-857521bd-5244-4781-9d0d-73e6dff90941.png)
这个地方写文武线三个字，何意？

**Comment by XiangyunHuang** [comment]
没啥具体意思，文档内容没咋打磨，以后还需改进，欢迎提 PR
