### ISSUE TITLE
想要咨询，为什么在Rstudio中Knit to pdf不在_book中生成pdf

### ISSUE THREAD

**Issue by fanzheng0352** [XiangyunHuang/ElegantBookdown#30]
在默认情况下（不适用elegantbookdown)的时候，我可以通过output: pdf_document输出pdf。
为什么我下载模板之后，无法生成pdf呢？
其他功能都完好。

**Comment by XiangyunHuang** [comment]
需要具体的 repo 我才好判断是什么原因？

**Comment by zhayuan87** [comment]
> 在默认情况下（不适用elegantbookdown)的时候，我可以通过output: pdf_document输出pdf。 为什么我下载模板之后，无法生成pdf呢？ 其他功能都完好。

很有可能是你latex没有安装好
