### ISSUE TITLE
ElegantBookdown 项目的起源

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/ElegantBookdown#5]
起源于在 GitHub 上闲逛，看到 https://github.com/ElegantLaTeX/ElegantBook 项目，被它的颜值吸引，便在 [统计之都论坛](https://d.cosx.org/) 开帖讨论 <https://d.cosx.org/d/420628-latex-elegantbook> 期间引来不少大佬 @yihui @pzhaonet @fyemath 围观，后来在现任老板 @sunbjt 怂恿下，决心开发这个项目

**Comment by lief-y** [comment]
我也是在GitHub上看到的 [https://github.com/ElegantLaTeX/ElegantBook](https://github.com/ElegantLaTeX/ElegantBook)。不过其中定理格式所使用的tcolorbox包，自己倒是在几年前就开始用。看到这个项目后，发现就不用自己设计版面格式了，太爽了。
后来看到@XiangyunHuang这个elegantbookdown项目，试了试，结果提示latex编译不过，当时还不知道怎么解决。直到前两个月，看到@yihui关于bookdown.post.latex介绍, 才算找到解决办法。期间还学了一点点pandoc lua filter的知识。收获不小。再次感谢@yihui 和@XiangyunHuang，也感谢ElegantBook项目的作者们 @EthanDeng和@Liam0205。

**Comment by yihui** [comment]
我都不知道你投奔 @sunbjt 了。伯乐相得千里马，皆大欢喜。

**Comment by Liam0205** [comment]
前几天正好在博客评论里撞见这个项目的作者，真是巧。

yihui 好，好久不见～
