### ISSUE TITLE
ElegantBookdown 更新计划

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/ElegantBookdown#8]
TeXLive 2020 发布了，上游 ElegantBook 似乎面临重大更新 https://github.com/ElegantLaTeX/ElegantBook/issues/93 上游对 LaTeX 宏包的依赖太多了 https://github.com/ElegantLaTeX/ElegantBook/issues/86 对字体的偏爱也很深，我的想法是让模版尽可能地保留灵活的空间，比如字体、参考文献样式

更新计划如下

- [x] 等待 ElegantBook 更新完成，至少 4.x 系列发布第二个版本 4.0/4.1
- [x] 启动 ElegantBookdown 的开发
- [x] HTML/PDF 本地编译成功，功能不增不减，不引入新的 LaTeX 依赖
- [x] Travis-CI 编译通过
- [x] 更新书籍📚至 bookdown.org
- [x] 发布 v0.8 版
- [x] 设置颜色主题可选

**Comment by XiangyunHuang** [comment]
ElegantBook v3.11 新版发布啦！很开心我们不需要更新模版，只需同步更新上游的宏包即可，模版稳定以来经受住了一次考验 🎉🎉  @fyemath

**Comment by EthanDeng** [comment]
> ElegantBook v3.11 新版发布啦！很开心我们不需要更新模版，只需同步更新上游的宏包即可，模版稳定以来经受住了一次考验 🎉🎉 @fyemath

现在不需要改动了么？那很优秀啊，其实有时候更新会想你们会不会要很大改动。

**Comment by XiangyunHuang** [comment]
@EthanDeng 应该不会因为 ElegantBook 而需要改动，因为我们对 ElegantBook 的侵入很小，仅有以下几行

https://github.com/XiangyunHuang/ElegantBookdown/blob/3719bc5526898e3283b7aa528932b46305a600cf/preamble.tex#L28-L36

**Comment by XiangyunHuang** [comment]
[ElegantBook](https://github.com/ElegantLaTeX/ElegantBook) 更新到 4.1 版本，再一次经受住考验，不需要变更模版

**Comment by XiangyunHuang** [comment]
[ElegantBook](https://github.com/ElegantLaTeX/ElegantBook) 更新到 4.4 版本，ElegantBookdown 简化了一些配置，这些配置大部分用户可能用不到。
